<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <title>Everything Everywhere - Software Engineer Technical Test</title>
    <link href="/assets/style.css" rel="stylesheet" type="text/css" media="screen" />
</head>
<body>
    <div id="wrapper">
        <div id="wrapper-top"></div>
        <div id="container">
            <div id="header">
                <h1>Everything Everywhere</h1>
                <ul id="logos">
                    <li>
                        <img src="/assets/logo-orange.gif" alt="Orange"/>
                    </li>
                    <li class="t-mobile">
                        <img src="/assets/logo-t-mobile.gif" alt="T-Mobile"/>
                    </li>
                </ul>
            </div>